In [ ]:
import pandas as pd
# To read the dataset
df = pd.read_csv(r"C:\Users\Tarun Sharma\OneDrive\Desktop\customer_shopping_behavior (1).csv")

In [ ]:
# To display 5 starting rows of dataset
print(df.head())

   Customer ID  Age Gender Item Purchased  Category  Purchase Amount (USD)  \
0            1   55   Male         Blouse  Clothing                     53
1            2   19   Male        Sweater  Clothing                     64
2            3   50   Male          Jeans  Clothing                     73
3            4   21   Male        Sandals  Footwear                     90
4            5   45   Male         Blouse  Clothing                     49

        Location Size      Color  Season  Review Rating Subscription Status  \
0       Kentucky    L       Gray  Winter            3.1                 Yes
1          Maine    L     Maroon  Winter            3.1                 Yes
2  Massachusetts    S     Maroon  Spring            3.1                 Yes
3   Rhode Island    M     Maroon  Spring            3.5                 Yes
4         Oregon    M  Turquoise  Spring            2.7                 Yes

   Shipping Type Discount Applied Promo Code Used  Previous Purchases  \
0        Express              Yes             Yes                  14
1        Express              Yes             Yes                   2
2  Free Shipping              Yes             Yes                  23
3   Next Day Air              Yes             Yes                  49
4  Free Shipping              Yes             Yes                  31

  Payment Method Frequency of Purchases
0          Venmo            Fortnightly
1           Cash            Fortnightly
2    Credit Card                 Weekly
3         PayPal                 Weekly
4         PayPal               Annually

In [3]:
# To get all the info of the dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [4]:
# To give the numeric summery of dataset
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [ ]:
# used to check the missing values column by column
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [ ]:
# replace the null values with median
df['Review Rating']= df.groupby('Category')['Review Rating'].transform(lambda x: x.x.medifillna(an()))

In [7]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [8]:
# snake casting
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [9]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [10]:
# create a column age_group
labels = ['Young Adult','Adult','Middle-aged','Senior']
df['age_group'] = pd.qcut(df['age'],q=4, labels= labels)

In [11]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

In [12]:
# create column purchase_frequency_days
frequency_mapping ={
    'Fortnightly':14,
    'Weekly': 7,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually' : 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days']= df['frequency_of_purchases'].map(frequency_mapping)

In [13]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                     14.0            Fortnightly
1                     14.0            Fortnightly
2                      7.0                 Weekly
3                      7.0                 Weekly
4                    365.0               Annually
5                      7.0                 Weekly
6                     90.0              Quarterly
7                      7.0                 Weekly
8                    365.0               Annually
9                     90.0              Quarterly

In [14]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [15]:
(df['discount_applied']==df['promo_code_used']).all()

np.True_

In [16]:
# remove one of the column
df = df.drop('promo_code_used',axis=1)

In [17]:
## Connect Python jupiter to mysql.-----------------------------

%pip install mysql-connector-python sqlalchemy pymysql

Requirement already satisfied: mysql-connector-python in c:\Users\Tarun Sharma\AppData\Local\Programs\Python\Python313\Lib\site-packages (9.6.0)
Requirement already satisfied: sqlalchemy in c:\Users\Tarun Sharma\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.0.50)
Requirement already satisfied: pymysql in c:\Users\Tarun Sharma\AppData\Local\Programs\Python\Python313\Lib\site-packages (1.2.0)
Requirement already satisfied: greenlet>=1 in c:\Users\Tarun Sharma\AppData\Local\Programs\Python\Python313\Lib\site-packages (from sqlalchemy) (3.5.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\Users\Tarun Sharma\AppData\Local\Programs\Python\Python313\Lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [30]:
import sqlalchemy
import pymysql

print("SQLAlchemy:",
sqlalchemy.__version__)
print("PyMySQL:",
pymysql.__version__)

SQLAlchemy: 2.0.50
PyMySQL: 2.2.8

In [31]:
import sqlalchemy 
print(sqlalchemy.__file__)

c:\Users\Tarun Sharma\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\__init__.py

In [32]:
import sqlalchemy
import pymysql

print("SQLAlchemy:", sqlalchemy.__version__)
print("PyMySQL:", pymysql.__version__)
print("SQLAlchemy path:", sqlalchemy.__file__)
print("PyMySQL path:", pymysql.__file__)

SQLAlchemy: 2.0.50
PyMySQL: 2.2.8
SQLAlchemy path: c:\Users\Tarun Sharma\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\__init__.py
PyMySQL path: c:\Users\Tarun Sharma\AppData\Local\Programs\Python\Python313\Lib\site-packages\pymysql\__init__.py

In [33]:
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:Tarun8505%40@localhost:3306/customer_nature")

print("Engine Created Successfully")

Engine Created Successfully

In [34]:
from sqlalchemy import text

with engine.connect() as conn:
    result = conn.execute(text("SELECT 1"))
    print("Database Connected Successfully")

Database Connected Successfully

In [35]:
df.to_sql(
    "customer",
    con=engine,
    if_exists="replace",
    index=False
)

print("Data Loaded Successfully")

Data Loaded Successfully